/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, OrthographicCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Model.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(()=> {
    setTimeout(()=> {
      console.log(actions)
      actions['Action.001'].play();
      actions['Action.001'].repetitions = 1;
      actions['Action.001'].clampWhenFinished = true;
  
      actions['Action.003'].play();
      actions['Action.003'].repetitions = 1;
      actions['Action.003'].clampWhenFinished = true;
      actions['Armature.001Action.001'].play();
      actions['Armature.001Action.001'].repetitions = 1;
      actions['Armature.001Action.001'].clampWhenFinished = true;
      actions['Armature.002Action'].play();
      actions['Armature.002Action'].repetitions = 1;
      actions['Armature.002Action'].clampWhenFinished = true;
      actions['Armature.003Action'].play();
      actions['Armature.003Action'].repetitions = 1;
      actions['Armature.003Action'].clampWhenFinished = true;
      actions['Armature.004Action'].play();
      actions['Armature.004Action'].repetitions = 1;
      actions['Armature.004Action'].clampWhenFinished = true;
      actions['Armature.006Action'].play();
      actions['Armature.006Action'].repetitions = 1;
      actions['Armature.006Action'].clampWhenFinished = true;

    },2000)
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-1.99, 3.47, -1.41]} rotation={[-0.64, -0.15, -1.57]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="wooden_wardrobe_wooden_wardrobe_mat_0003" geometry={nodes.wooden_wardrobe_wooden_wardrobe_mat_0003.geometry} material={materials.wooden_wardrobe_mat} skeleton={nodes.wooden_wardrobe_wooden_wardrobe_mat_0003.skeleton} />
        </group>
        <group name="Armature001" position={[0.58, 3.56, -1.41]} rotation={[0, 0, 1.54]}>
          <primitive object={nodes.Bone_1} />
          <skinnedMesh name="wooden_wardrobe_wooden_wardrobe_mat_0002" geometry={nodes.wooden_wardrobe_wooden_wardrobe_mat_0002.geometry} material={materials.wooden_wardrobe_mat} skeleton={nodes.wooden_wardrobe_wooden_wardrobe_mat_0002.skeleton} />
        </group>
        <group name="Sketchfab_model002" position={[-0.46, 2.91, -0.11]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="be9dd71d317e4b209641b3669fecf4a9fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode001">
              <group name="Model">
                <group name="Component_4_1">
                  <group name="Mesh71" />
                </group>
                <group name="Componente_35_1">
                  <group name="Component_1_1">
                    <group name="Mesh63" />
                  </group>
                  <group name="Component_1_2">
                    <group name="Mesh64" />
                  </group>
                </group>
                <group name="Componente_35_2">
                  <group name="Component_1_3">
                    <group name="Mesh65" />
                  </group>
                  <group name="Component_1_4">
                    <group name="Mesh66" />
                  </group>
                </group>
                <group name="Componente_35_3">
                  <group name="Component_1_5">
                    <group name="Mesh67" />
                  </group>
                  <group name="Component_1_6">
                    <group name="Mesh68" />
                  </group>
                </group>
                <group name="Componente_35_4">
                  <group name="Component_1_7">
                    <group name="Mesh69" />
                  </group>
                  <group name="Component_1_8">
                    <group name="Mesh70" />
                  </group>
                </group>
                <group name="Group1">
                  <group name="Group2">
                    <group name="Mesh1" />
                  </group>
                  <group name="Group3">
                    <group name="Mesh2" />
                  </group>
                  <group name="Group4">
                    <group name="Mesh3" />
                  </group>
                  <group name="Group5">
                    <group name="Mesh4" />
                  </group>
                  <group name="Group6">
                    <group name="Mesh5" />
                  </group>
                  <group name="Group7">
                    <group name="Mesh6" />
                  </group>
                  <group name="Group8">
                    <group name="Mesh7" />
                  </group>
                  <group name="Mesh8" />
                </group>
                <group name="Group10">
                  <group name="Group11">
                    <group name="Mesh10" />
                  </group>
                  <group name="Group12">
                    <group name="Mesh11" />
                  </group>
                  <group name="Group13">
                    <group name="Mesh12" />
                  </group>
                  <group name="Group14">
                    <group name="Mesh13" />
                  </group>
                  <group name="Group15">
                    <group name="Mesh14" />
                  </group>
                  <group name="Group16">
                    <group name="Mesh15" />
                  </group>
                  <group name="Group17">
                    <group name="Mesh16" />
                  </group>
                  <group name="Mesh17" />
                </group>
                <group name="Group18">
                  <group name="Mesh18" />
                </group>
                <group name="Group19">
                  <group name="Mesh19" />
                </group>
                <group name="Group20">
                  <group name="Mesh20" />
                </group>
                <group name="Group21">
                  <group name="Group22">
                    <group name="Mesh21" />
                  </group>
                  <group name="Group23">
                    <group name="Mesh22" />
                  </group>
                  <group name="Group24">
                    <group name="Mesh23" />
                  </group>
                  <group name="Group25">
                    <group name="Mesh24" />
                  </group>
                  <group name="Group26">
                    <group name="Mesh25" />
                  </group>
                  <group name="Group27">
                    <group name="Mesh26" />
                  </group>
                  <group name="Group28">
                    <group name="Mesh27" />
                  </group>
                  <group name="Mesh28" />
                </group>
                <group name="Group29">
                  <group name="Line05__30___50___68_">
                    <group name="Mesh33" />
                  </group>
                  <group name="Line07__30___50___68_">
                    <group name="Mesh32" />
                  </group>
                  <group name="Line25__30___50___68_">
                    <group name="Mesh29" />
                  </group>
                  <group name="Line27__30___50___68_">
                    <group name="Mesh36" />
                  </group>
                  <group name="Line27__30___50___68_1">
                    <group name="Mesh38" />
                  </group>
                  <group name="Line28__30___50___68_">
                    <group name="Mesh35" />
                  </group>
                  <group name="Line28__30___50___68_1">
                    <group name="Mesh37" />
                  </group>
                  <group name="Plane04__30___50___68_">
                    <group name="Mesh31" />
                  </group>
                  <group name="Plane09__30___50___68_">
                    <group name="Mesh34" />
                  </group>
                  <group name="Plane31__30___50___68_">
                    <group name="Mesh30" />
                  </group>
                </group>
                <group name="Group30">
                  <group name="Group31">
                    <group name="Mesh39" />
                  </group>
                  <group name="Group32">
                    <group name="Mesh40" />
                  </group>
                  <group name="Group33">
                    <group name="Mesh41" />
                  </group>
                  <group name="Group34">
                    <group name="Mesh42" />
                  </group>
                  <group name="Group35">
                    <group name="Mesh43" />
                  </group>
                  <group name="Group36">
                    <group name="Mesh44" />
                  </group>
                  <group name="Group37">
                    <group name="Mesh45" />
                  </group>
                  <group name="Mesh46" />
                </group>
                <group name="Group38">
                  <group name="Line05__30___50___68_1">
                    <group name="Mesh51" />
                  </group>
                  <group name="Line07__30___50___68_1">
                    <group name="Mesh50">
                      <group name="Mesh50_Material__14_0" position={[-2105.24, -731.51, -277.84]} scale={2.97}>
                        <mesh name="Mesh50_Material__14_0_1" geometry={nodes.Mesh50_Material__14_0_1.geometry} material={materials.Material__14} />
                        <mesh name="Mesh50_Material__14_0_2" geometry={nodes.Mesh50_Material__14_0_2.geometry} material={materials['Material__9.001']} />
                      </group>
                    </group>
                  </group>
                  <group name="Line25__30___50___68_1">
                    <group name="Mesh47" />
                  </group>
                  <group name="Line27__30___50___68_2">
                    <group name="Mesh54">
                      <group name="Mesh54_chromium1_0" position={[-1925.11, -726.59, -258.39]} scale={2.97}>
                        <mesh name="Mesh54_chromium1_0_1" geometry={nodes.Mesh54_chromium1_0_1.geometry} material={materials['chromium1.001']} />
                        <mesh name="Mesh54_chromium1_0_2" geometry={nodes.Mesh54_chromium1_0_2.geometry} material={materials['Material__10.001']} />
                      </group>
                    </group>
                  </group>
                  <group name="Line27__30___50___68_3">
                    <group name="Mesh56" />
                  </group>
                  <group name="Line28__30___50___68_2">
                    <group name="Mesh53" />
                  </group>
                  <group name="Line28__30___50___68_3">
                    <group name="Mesh55" />
                  </group>
                  <group name="Plane04__30___50___68_1">
                    <group name="Mesh49" />
                  </group>
                  <group name="Plane09__30___50___68_1">
                    <group name="Mesh52">
                      <group name="Mesh52_svetr_yzor1_0" position={[-2092.21, -725.79, -256.29]} scale={2.97}>
                        <mesh name="Mesh52_svetr_yzor1_0_1" geometry={nodes.Mesh52_svetr_yzor1_0_1.geometry} material={materials['svetr_yzor1.001']} />
                        <mesh name="Mesh52_svetr_yzor1_0_2" geometry={nodes.Mesh52_svetr_yzor1_0_2.geometry} material={materials['chromium1.001']} />
                        <mesh name="Mesh52_svetr_yzor1_0_3" geometry={nodes.Mesh52_svetr_yzor1_0_3.geometry} material={materials['svetr_verh1.001']} />
                      </group>
                    </group>
                  </group>
                  <group name="Plane31__30___50___68_1">
                    <group name="Mesh48" />
                  </group>
                </group>
                <group name="Group39">
                  <group name="Mesh57" />
                </group>
                <group name="Group9">
                  <group name="Mesh9" />
                </group>
                <group name="Mesh72" />
                <group name="towel_rolled1">
                  <group name="Group40">
                    <group name="Mesh58" />
                  </group>
                  <group name="Group41">
                    <group name="Mesh59" />
                  </group>
                  <group name="Group42">
                    <group name="Mesh60" />
                  </group>
                  <group name="Group43">
                    <group name="Mesh61" />
                  </group>
                  <group name="Group44">
                    <group name="Mesh62" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Area" position={[-0.2, 9.14, 0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={0.67} />
        <group name="Area001" position={[-5.75, 3.18, -4.8]} rotation={[-Math.PI / 2, 0, 0]} scale={0.67} />
        <group name="Cube006" position={[-3.77, 5.06, 0.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -1.41, -1.73]} />
        <group name="Circle007" />
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="wooden_wardrobefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="wooden_wardrobe">
                <mesh name="wooden_wardrobe_wooden_wardrobe_mat_0001" geometry={nodes.wooden_wardrobe_wooden_wardrobe_mat_0001.geometry} material={materials['Material.014']} position={[-66.54, 4.11, -250.38]} scale={3.33} />
              </group>
            </group>
          </group>
        </group>
        <group name="Armature002" position={[2.01, 1.48, 2.14]} rotation={[0, -Math.PI / 2, 0]} scale={1.17}>
          <primitive object={nodes.Bone_2} />
          <primitive object={nodes.neutral_bone} />
          <group name="Cube">
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Material} skeleton={nodes.Mesh_1.skeleton} />
            <skinnedMesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials['Material.011']} skeleton={nodes.Mesh_2.skeleton} />
            <skinnedMesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials['Material.010']} skeleton={nodes.Mesh_3.skeleton} />
            <skinnedMesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials['Material.027']} skeleton={nodes.Mesh_4.skeleton} />
            <skinnedMesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials['Material.026']} skeleton={nodes.Mesh_5.skeleton} />
            <skinnedMesh name="Mesh_6" geometry={nodes.Mesh_6.geometry} material={materials['Material.013']} skeleton={nodes.Mesh_6.skeleton} />
            <skinnedMesh name="Mesh_7" geometry={nodes.Mesh_7.geometry} material={materials['Material.018']} skeleton={nodes.Mesh_7.skeleton} />
            <skinnedMesh name="Mesh_8" geometry={nodes.Mesh_8.geometry} material={materials['Material.020']} skeleton={nodes.Mesh_8.skeleton} />
            <skinnedMesh name="Mesh_9" geometry={nodes.Mesh_9.geometry} material={materials['Material.019']} skeleton={nodes.Mesh_9.skeleton} />
          </group>
        </group>
        <group name="Armature004" position={[2.03, 1.97, 2.78]} rotation={[-1.52, 1.57, -1.62]} scale={0.52}>
          <primitive object={nodes.Bone_3} />
          <skinnedMesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.022']} skeleton={nodes.Cube012.skeleton} />
        </group>
        <group name="Armature003" position={[2.03, 1.97, 1.45]} rotation={[-1.52, 1.57, -1.62]} scale={0.52}>
          <primitive object={nodes.Bone_4} />
          <skinnedMesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.023']} skeleton={nodes.Cube009.skeleton} />
        </group>
        <group name="Armature005" position={[2.02, 1.42, 1.75]} rotation={[1.57, 0.05, 1.57]} scale={0.35}>
          <primitive object={nodes.Bone_5} />
          <skinnedMesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.024']} skeleton={nodes.Cube011.skeleton} />
        </group>
        <group name="Armature006" position={[2.05, 1.42, 2.49]} rotation={[1.57, 0.12, 1.57]} scale={0.35}>
          <primitive object={nodes.Bone_6} />
          <skinnedMesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.025']} skeleton={nodes.Cube008.skeleton} />
        </group>
        <OrthographicCamera name="Camera" makeDefault={true} zoom={30} far={1000} near={0.1} position={[16.34, 18.51, 19.75]} rotation={[-0.63, 0.59, 0.39]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[0, 4, 0]} scale={4} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.004']} position={[2.97, 0.47, 1.08]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[0, 0.02, 0]} scale={[1, 1.05, 1]} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.004']} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[0, 0.13, 0]} />
        </mesh>
        <group name="Plane005" position={[-0.5, 0.42, 1.4]} rotation={[0, 0.01, 0]} scale={0.84}>
          <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials['Material.005']} />
          <mesh name="Plane005_2" geometry={nodes.Plane005_2.geometry} material={materials['Material.004']} />
        </group>
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.007']} position={[3.1, 0.2, -2.97]} rotation={[0, -1.01, 0]} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.007']} position={[3.1, 6.57, -2.97]} rotation={[0, -1.01, 0]} scale={0.23} />
        <mesh name="Roundcube" geometry={nodes.Roundcube.geometry} material={materials['Material.007']} position={[3.1, 6.44, -2.97]} rotation={[0, -1.01, 0]} scale={0.21} />
        <mesh name="Vert" geometry={nodes.Vert.geometry} material={materials['Material.007']} position={[3.1, 6.69, -2.97]} rotation={[0, -0.64, 0]} scale={1.24}>
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.017']} position={[0, -0.18, 1.34]} scale={0.78}>
            <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.004']} scale={[1, 1.16, 1]} />
          </mesh>
        </mesh>
        <group name="Plane009" position={[-2.98, 0.3, 1.32]} rotation={[Math.PI, -0.03, Math.PI]} scale={0.87}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.005']} />
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['Material.007']} />
          <mesh name="Roundcube002" geometry={nodes.Roundcube002.geometry} material={materials['Material.008']} position={[0, 2.72, 0.48]} scale={0.03} />
          <mesh name="Vert001" geometry={nodes.Vert001.geometry} material={materials['Material.007']} position={[-0.07, 0.15, -0.14]} />
        </group>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0, 4.23, 0]} scale={4} />
        <group name="Cube004" position={[-3.77, 5.06, 0.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -1.41, -1.73]}>
          <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials['Material.009']} />
          <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials['Material.016']} />
        </group>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[-3.77, 5.06, 0.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -1.41, -1.73]} />
        <group name="Cube010" position={[-0.15, 4, 0]} scale={4}>
          <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials['Material.001']} />
          <mesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={materials['Material.002']} />
          <mesh name="Cube010_3" geometry={nodes.Cube010_3.geometry} material={materials['Material.002']} />
        </group>
        <group name="Cylinder" position={[-2.04, 4.78, -2.27]} rotation={[0, 0, -1.56]} scale={-0.06}>
          <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials.wooden_wardrobe_mat} />
          <mesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials['<Silver>']} />
        </group>
      </group>
    </group>
  )
}

export default Model;